# Generated by Django 4.2.28 on 2026-04-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_records', to='qms.measurementequipment'),
        ),
    ]
