# Generated by Django 4.2.28 on 2026-05-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('qms', '0002_alter_calibrationrecord_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginspection',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_inspections', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='incominginspection',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_inspections', to='procurement.supplier'),
        ),
    ]
