# Generated by Django 4.2.28 on 2026-05-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eam', '0001_initial'),
        ('qms', '0003_incominginspection_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementequipment',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_equipment', to='eam.asset'),
        ),
    ]
