# Generated by Django 4.2.28 on 2026-05-09 13:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='benchmarksnapshot',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
