# Generated by Django 4.2.28 on 2026-05-13 20:34

import apps.sales.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_goodsreceiptnote_purchase_order_and_more'),
        ('plm', '0007_productcompliancesignature'),
        ('core', '0002_tenant_require_compliance_e_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('customer_class', models.CharField(choices=[('key', 'Key Account'), ('standard', 'Standard'), ('distributor', 'Distributor / Reseller'), ('one_time', 'One-time / Walk-in')], default='standard', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=60)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_terms', models.CharField(choices=[('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid'), ('net15', 'Net 15'), ('net30', 'Net 30'), ('net45', 'Net 45'), ('net60', 'Net 60'), ('net90', 'Net 90')], default='net30', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Hard cap on total open AR + unfulfilled orders.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_used', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Denormalised running total. Recompute via management command.', max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_hold', 'On Hold'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('risk_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Tenant-wide fallback when a customer has no price list set.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('nda', 'NDA'), ('msa', 'Master Service Agreement'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('other', 'Other')], default='contract', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='sales/customer-docs/%Y/%m/', validators=[apps.sales.models._validate_customer_doc])),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_customer_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('buyer', 'Buyer / Purchasing'), ('accounts', 'Accounts Payable'), ('shipping', 'Receiving / Logistics'), ('technical', 'Technical / Engineering'), ('executive', 'Executive'), ('other', 'Other')], default='buyer', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_alt', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sales.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['customer', '-is_primary', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sales.customercategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Customer categories',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='sales.customercategory'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='sales.pricelist'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('sms', 'SMS / Text')], default='note', max_length=10)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], default='outbound', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='done', max_length=20)),
                ('related_order_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='sales.customercontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_communications', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='sales.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_qty', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Tier break - this row applies when ordered qty >= min_qty.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_price_items', to='plm.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['price_list', 'product', 'min_qty'],
                'unique_together': {('price_list', 'product', 'min_qty')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'code')},
        ),
    ]
