# Generated by Django 4.2.28 on 2026-05-13 21:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_atpcalculation_ctpcalculation_deliveryroute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of line gross (qty x unit_price), pre-discount.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of line gross (qty x unit_price), pre-discount.', max_digits=14),
        ),
    ]
