# Generated by Django 4.2.28 on 2026-04-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CADDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drawing_number', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('2d_drawing', '2D Drawing'), ('3d_model', '3D Model'), ('schematic', 'Schematic'), ('pcb', 'PCB Layout'), ('assembly', 'Assembly Drawing'), ('other', 'Other')], default='2d_drawing', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['drawing_number'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(choices=[('global', 'Global'), ('us', 'United States'), ('eu', 'Europe'), ('apac', 'Asia-Pacific'), ('other', 'Other')], default='global', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NPIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('current_stage', models.CharField(choices=[('concept', 'Concept'), ('feasibility', 'Feasibility'), ('design', 'Design'), ('development', 'Development'), ('validation', 'Validation'), ('pilot_production', 'Pilot Production'), ('launch', 'Launch')], default='concept', max_length=20)),
                ('target_launch_date', models.DateField(blank=True, null=True)),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('component', 'Component'), ('sub_assembly', 'Sub-Assembly'), ('finished_good', 'Finished Good'), ('service', 'Service')], default='component', max_length=20)),
                ('unit_of_measure', models.CharField(choices=[('ea', 'Each'), ('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound'), ('m', 'Meter'), ('cm', 'Centimeter'), ('l', 'Liter'), ('ml', 'Milliliter'), ('box', 'Box'), ('set', 'Set')], default='ea', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('obsolete', 'Obsolete'), ('phased_out', 'Phased Out')], default='draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plm/products/')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_code', models.CharField(max_length=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('change_notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='plm.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['product', 'revision_code'],
                'unique_together': {('product', 'revision_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spec_type', models.CharField(choices=[('physical', 'Physical'), ('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('chemical', 'Chemical'), ('performance', 'Performance'), ('other', 'Other')], default='other', max_length=20)),
                ('key', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='plm.product')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to='plm.productrevision')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['spec_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ProductCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('certification_number', models.CharField(blank=True, max_length=120)),
                ('issuing_body', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='plm/compliance/')),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='plm.product')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_records', to='plm.compliancestandard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'product', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='plm.productcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='plm.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plm.productrevision'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='NPIStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('concept', 'Concept'), ('feasibility', 'Feasibility'), ('design', 'Design'), ('development', 'Development'), ('validation', 'Validation'), ('pilot_production', 'Pilot Production'), ('launch', 'Launch')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('gate_decision', models.CharField(choices=[('pending', 'Pending'), ('go', 'Go'), ('no_go', 'No-Go'), ('recycle', 'Recycle')], default='pending', max_length=20)),
                ('gate_notes', models.TextField(blank=True)),
                ('gate_decided_at', models.DateTimeField(blank=True, null=True)),
                ('gate_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_decisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='plm.npiproject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['project', 'sequence'],
                'unique_together': {('project', 'stage')},
            },
        ),
        migrations.AddField(
            model_name='npiproject',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npi_projects', to='plm.product'),
        ),
        migrations.AddField(
            model_name='npiproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npi_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npiproject',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='NPIDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npi_deliverables', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='plm.npistage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['stage', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('change_type', models.CharField(choices=[('design', 'Design'), ('specification', 'Specification'), ('material', 'Material'), ('process', 'Process'), ('documentation', 'Documentation')], default='design', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_implementation_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ecos', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ECOImpactedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_summary', models.TextField(blank=True)),
                ('after_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_after', to='plm.productrevision')),
                ('before_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_before', to='plm.productrevision')),
                ('eco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacted_items', to='plm.engineeringchangeorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eco_items', to='plm.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['product__sku'],
            },
        ),
        migrations.CreateModel(
            name='ECOAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='plm/eco/')),
                ('eco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='plm.engineeringchangeorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECOApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eco_approvals', to=settings.AUTH_USER_MODEL)),
                ('eco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='plm.engineeringchangeorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CADDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='plm/cad/')),
                ('change_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='plm.caddocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cad_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document', '-created_at'],
                'unique_together': {('document', 'version')},
            },
        ),
        migrations.AddField(
            model_name='caddocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plm.caddocumentversion'),
        ),
        migrations.AddField(
            model_name='caddocument',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cad_documents', to='plm.product'),
        ),
        migrations.AddField(
            model_name='caddocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_sku', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='plm.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['variant_sku'],
                'unique_together': {('tenant', 'variant_sku')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='npiproject',
            unique_together={('tenant', 'code')},
        ),
        migrations.CreateModel(
            name='ComplianceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('note_added', 'Note Added')], max_length=30)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='plm.productcompliance')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['compliance', '-performed_at'], name='plm_complia_complia_47426b_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='caddocument',
            unique_together={('tenant', 'drawing_number')},
        ),
    ]
