# Generated by Django 4.2.28 on 2026-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking_mode',
            field=models.CharField(choices=[('none', 'None'), ('lot', 'Lot Tracked'), ('serial', 'Serial Tracked'), ('lot_and_serial', 'Lot + Serial')], default='none', help_text='Inventory traceability mode (Module 8): none / lot / serial / lot_and_serial', max_length=20),
        ),
    ]
