# Generated by Django 4.2.28 on 2026-05-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
        ('plm', '0002_product_tracking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Drives direct-labor allocation when MES production is reported.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='labor.costcenter'),
        ),
    ]
