# Generated by Django 4.2.28 on 2026-05-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0004_product_standard_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceauditlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='complianceauditlog',
            name='this_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
