# Generated by Django 4.2.28 on 2026-05-09 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_tenant_require_compliance_e_signature'),
        ('plm', '0006_backfill_compliance_audit_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComplianceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('typed_name', models.CharField(help_text='Full legal name as typed by the signer at the moment of signing.', max_length=200)),
                ('role', models.CharField(blank=True, help_text='Signer’s role / title at the time of signing.', max_length=120)),
                ('reason', models.CharField(choices=[('initial_certification', 'Initial Certification'), ('renewal', 'Renewal'), ('reaffirmation', 'Reaffirmation'), ('correction', 'Correction')], default='initial_certification', max_length=30)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('compliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='plm.productcompliance')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_compliance_signatures', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['tenant', 'compliance', '-signed_at'], name='plm_product_tenant__5df5f6_idx')],
            },
        ),
    ]
