# Generated by Django 4.2.28 on 2026-05-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supplier_company',
            field=models.ForeignKey(blank=True, help_text="Set only when role='supplier'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='procurement.supplier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('production_manager', 'Production Manager'), ('plant_manager', 'Plant Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('quality_inspector', 'Quality Inspector'), ('warehouse_staff', 'Warehouse Staff'), ('procurement', 'Procurement'), ('accountant', 'Accountant'), ('viewer', 'Viewer'), ('supplier', 'Supplier (External)')], default='operator', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('production_manager', 'Production Manager'), ('plant_manager', 'Plant Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('quality_inspector', 'Quality Inspector'), ('warehouse_staff', 'Warehouse Staff'), ('procurement', 'Procurement'), ('accountant', 'Accountant'), ('viewer', 'Viewer'), ('supplier', 'Supplier (External)')], default='operator', max_length=30),
        ),
    ]
