# Generated by Django 4.2.28 on 2026-05-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('mrp', '0002_mrprun_protect_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrppurchaserequisition',
            name='converted_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requisitions', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='mrppurchaserequisition',
            name='converted_reference',
            field=models.CharField(blank=True, help_text='Free-text reference to the converted PO (legacy / kept for back-compat).', max_length=120),
        ),
    ]
