# Generated by Django 4.2.28 on 2026-04-27 20:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecast',
            name='confidence_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('80'), help_text='Forecast confidence — 0-100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='demandforecast',
            name='forecast_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='mpsline',
            name='available_to_promise',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='mpsline',
            name='firm_planned_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='mpsline',
            name='forecast_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='mpsline',
            name='scheduled_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='optimizationobjective',
            name='weight_changeovers',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Relative penalty for grouping unlike products together.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='optimizationobjective',
            name='weight_idle',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Relative penalty for idle time on work centers.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='optimizationobjective',
            name='weight_lateness',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Relative penalty for missing requested due dates.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='optimizationobjective',
            name='weight_priority',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Relative reward for honoring priority on rush orders.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='move_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='queue_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='run_minutes_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='setup_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='capacity_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Throughput target in units/hour at 100% efficiency.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='efficiency_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Realized efficiency — 0-100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
