# Generated by Django 4.2.28 on 2026-05-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_atpcalculation_ctpcalculation_deliveryroute_and_more'),
        ('pps', '0002_alter_demandforecast_confidence_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='source_sales_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_production_orders', to='sales.salesorderline'),
        ),
    ]
