# Generated by Django 4.2.28 on 2026-05-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='require_compliance_e_signature',
            field=models.BooleanField(default=False, help_text='When True, every transition of a `plm.ProductCompliance` record INTO status=`compliant` must be accompanied by an electronic signature (FDA 21 CFR Part 11). Off by default to preserve backward-compatibility with seed data and the existing test suite; turn on per regulated-industry tenant.'),
        ),
    ]
