# Generated by Django 4.2.28 on 2026-05-09 13:17

import apps.compliance.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_goodsreceiptnote_purchase_order_and_more'),
        ('mes', '0003_shopflooroperator_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plm', '0004_product_standard_sale_price'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_number', models.CharField(max_length=15)),
                ('doc_type', models.CharField(choices=[('iso_9001', 'ISO 9001 QMS'), ('iso_14001', 'ISO 14001 EMS'), ('iso_45001', 'ISO 45001 OHSAS'), ('sop', 'Standard Operating Procedure'), ('wi', 'Work Instruction'), ('form', 'Form / Record'), ('policy', 'Policy'), ('other', 'Other')], default='sop', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('effective', 'Effective'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=15)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.compliance.models.compliance_doc_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_compliance_docs', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='compliance.compliancedocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['doc_number', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recall_number', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('class_i', 'Class I - Probable serious health consequence'), ('class_ii', 'Class II - Possible reversible health consequence'), ('class_iii', 'Class III - Unlikely health consequence')], default='class_iii', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='initiated', max_length=15)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('affected_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Total units across all affected lots (denorm — recomputed).', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('recovered_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_recalls', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_recalls', to='plm.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_number', models.CharField(max_length=15)),
                ('scheduled_for', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pass_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('na_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('hazard_class', models.CharField(choices=[('hazardous_chemical', 'Hazardous Chemical'), ('e_waste', 'Electronic Waste'), ('biohazard', 'Biohazardous'), ('radioactive', 'Radioactive'), ('general', 'General / Solid'), ('recyclable', 'Recyclable'), ('liquid', 'Liquid Waste')], default='general', max_length=20)),
                ('epa_code', models.CharField(blank=True, help_text='Optional EPA / regulatory waste code (e.g. D001, F003).', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WasteManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest_number', models.CharField(max_length=15)),
                ('generator', models.CharField(help_text='Generator (this facility).', max_length=200)),
                ('transporter', models.CharField(blank=True, max_length=200)),
                ('disposal_facility', models.CharField(blank=True, max_length=200)),
                ('epa_id', models.CharField(blank=True, max_length=30)),
                ('manifest_date', models.DateField()),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_transit', 'In Transit'), ('disposed', 'Disposed'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('total_quantity_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifests', to='compliance.wastecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-manifest_date'],
            },
        ),
        migrations.CreateModel(
            name='WasteDisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('quantity_kg', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('container_type', models.CharField(choices=[('drum_55gal', '55-gal Drum'), ('tote_330gal', '330-gal IBC Tote'), ('cubic_yard', 'Cubic-Yard Box'), ('bag', 'Bag'), ('other', 'Other')], default='drum_55gal', max_length=15)),
                ('container_count', models.PositiveSmallIntegerField(default=1)),
                ('disposal_method', models.CharField(choices=[('landfill', 'Landfill'), ('incineration', 'Incineration'), ('recycling', 'Recycling / Recovery'), ('treatment', 'Treatment'), ('reuse', 'Reuse'), ('storage', 'Permanent Storage')], default='landfill', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_records', to='compliance.wastemanifest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['manifest', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_order', models.PositiveSmallIntegerField()),
                ('question', models.CharField(max_length=400)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='na', max_length=4)),
                ('finding', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='compliance.safetyaudit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['audit', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAuditChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='safetyaudit',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='compliance.safetyauditchecklist'),
        ),
        migrations.AddField(
            model_name='safetyaudit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_audits', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='safetyaudit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_number', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('hazard', models.TextField()),
                ('likelihood', models.PositiveSmallIntegerField(help_text='1 (rare) - 5 (almost certain)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('severity', models.PositiveSmallIntegerField(help_text='1 (negligible) - 5 (catastrophic)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_score', models.PositiveSmallIntegerField(default=1)),
                ('control_measures', models.TextField(blank=True)),
                ('residual_likelihood', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_severity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='inventory.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-risk_score', 'assessment_number'],
            },
        ),
        migrations.CreateModel(
            name='RecallNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_number', models.CharField(max_length=15)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('letter', 'Letter'), ('press_release', 'Press Release'), ('website', 'Website Banner'), ('regulatory', 'Regulatory Filing')], default='email', max_length=15)),
                ('audience', models.CharField(help_text='Customer segment / distributor / regulator name.', max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], default='draft', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='compliance.productrecall')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-sent_at', 'notice_number'],
            },
        ),
        migrations.CreateModel(
            name='RecallAffectedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('recovered_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_links', to='inventory.lot')),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_lots', to='compliance.productrecall')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['recall', 'lot'],
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('injury', 'Personal Injury'), ('near_miss', 'Near Miss'), ('environmental', 'Environmental'), ('property_damage', 'Property Damage'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_number', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('severity', models.CharField(choices=[('low', 'Low - First Aid'), ('medium', 'Medium - Medical Treatment'), ('high', 'High - Lost Time'), ('critical', 'Critical - Fatality / Major')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('corrective_action', 'Corrective Action'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('witnesses', models.TextField(blank=True, help_text='Comma-separated names or descriptions.')),
                ('immediate_actions', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to=settings.AUTH_USER_MODEL)),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='compliance.incidenttype')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_incidents', to='inventory.warehouse')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('source_andon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_incidents', to='mes.andonalert')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('typed_name', models.CharField(help_text='Full legal name as typed by the signer.', max_length=200)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(choices=[('authorship', 'Authorship'), ('review', 'Review'), ('approval', 'Approval'), ('responsibility', 'Responsibility'), ('verification', 'Verification')], default='approval', max_length=20)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='compliance.compliancedocument')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submit', 'Submitted for Review'), ('approve', 'Approved'), ('reject', 'Rejected'), ('publish', 'Published as Effective'), ('supersede', 'Superseded'), ('retire', 'Retired')], max_length=15)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_approvals', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='compliance.compliancedocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-acted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_number', models.CharField(max_length=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('hash_chain', models.CharField(blank=True, help_text='SHA-256 hex digest of previous_chain || archived rows.', max_length=64)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_compliance_archives', to=settings.AUTH_USER_MODEL)),
                ('previous_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_archives', to='compliance.auditlogarchive')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddIndex(
            model_name='wastemanifest',
            index=models.Index(fields=['tenant', 'status', '-manifest_date'], name='compliance__tenant__450947_idx'),
        ),
        migrations.AddIndex(
            model_name='wastemanifest',
            index=models.Index(fields=['tenant', 'category'], name='compliance__tenant__06af22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wastemanifest',
            unique_together={('tenant', 'manifest_number')},
        ),
        migrations.AlterUniqueTogether(
            name='wastedisposalrecord',
            unique_together={('manifest', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='wastecategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='safetyaudititem',
            unique_together={('audit', 'item_order')},
        ),
        migrations.AlterUniqueTogether(
            name='safetyauditchecklist',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='safetyaudit',
            index=models.Index(fields=['tenant', 'status', '-scheduled_for'], name='compliance__tenant__906fac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='safetyaudit',
            unique_together={('tenant', 'audit_number')},
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['tenant', 'status', '-risk_score'], name='compliance__tenant__c1afd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskassessment',
            unique_together={('tenant', 'assessment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='recallnotice',
            unique_together={('tenant', 'notice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='recallaffectedlot',
            unique_together={('recall', 'lot')},
        ),
        migrations.AddIndex(
            model_name='productrecall',
            index=models.Index(fields=['tenant', 'status', '-initiated_at'], name='compliance__tenant__6bce32_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecall',
            index=models.Index(fields=['tenant', 'severity'], name='compliance__tenant__109bf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecall',
            unique_together={('tenant', 'recall_number')},
        ),
        migrations.AlterUniqueTogether(
            name='incidenttype',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['tenant', 'status', '-occurred_at'], name='compliance__tenant__ffa95b_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['tenant', 'severity'], name='compliance__tenant__7bb84c_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('source_andon__isnull', False)), fields=('source_andon',), name='compliance_incident_unique_andon'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentreport',
            unique_together={('tenant', 'incident_number')},
        ),
        migrations.AddIndex(
            model_name='electronicsignature',
            index=models.Index(fields=['tenant', 'document', '-signed_at'], name='compliance__tenant__b74821_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['tenant', 'document', '-acted_at'], name='compliance__tenant__eb0277_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancedocument',
            index=models.Index(fields=['tenant', 'doc_type', 'status'], name='compliance__tenant__f9fa00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancedocument',
            unique_together={('tenant', 'doc_number'), ('tenant', 'doc_number', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='auditlogarchive',
            unique_together={('tenant', 'archive_number'), ('tenant', 'period_start', 'period_end')},
        ),
    ]
