# Generated by Django 4.2.28 on 2026-05-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0004_measurementequipment_asset'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='source_ncr',
            field=models.ForeignKey(blank=True, help_text='Auto-populated when a critical NCR triggers an incident report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_incidents', to='qms.nonconformancereport'),
        ),
        migrations.AddConstraint(
            model_name='incidentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ncr__isnull', False)), fields=('source_ncr',), name='compliance_incident_unique_ncr'),
        ),
    ]
