# Generated by Django 4.2.28 on 2026-05-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_incidentreport_source_ncr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recallaffectedlot',
            name='last_leak_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent post-recall outbound movement.', null=True),
        ),
        migrations.AddField(
            model_name='recallaffectedlot',
            name='post_recall_movement_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of outbound StockMovements posted on this lot AFTER the recall was filed.'),
        ),
    ]
