# Generated by Django 4.2.28 on 2026-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_recallaffectedlot_last_leak_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recallnotice',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Required when channel=email; left blank for non-email channels.', max_length=254),
        ),
    ]
