# Generated by Django 4.2.28 on 2026-05-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
        ('eam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Drives indirect-labor allocation when MWO labor is logged.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='labor.costcenter'),
        ),
    ]
