# Generated by Django 4.2.28 on 2026-05-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
        ('eam', '0002_asset_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionreading',
            name='source_iot_reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_reading', to='iot.iotreading'),
        ),
        migrations.AddField(
            model_name='failureprediction',
            name='source_anomaly',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_prediction', to='iot.anomalydetection'),
        ),
    ]
