# Generated by Django 4.2.28 on 2026-05-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='procurement.supplier'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Free-text supplier (preserved for legacy GRNs - new GRNs should use the FK).', max_length=255),
        ),
    ]
