# Generated by Django 4.2.28 on 2026-05-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_atpcalculation_ctpcalculation_deliveryroute_and_more'),
        ('inventory', '0002_goodsreceiptnote_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='source_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.shipment'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_shipment_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.shipmentline'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('production_in', 'Production In'), ('production_out', 'Production Out'), ('scrap', 'Scrap'), ('cycle_count', 'Cycle Count Variance'), ('shipment_out', 'Sales Shipment Out')], max_length=20),
        ),
    ]
