# Generated by Django 4.2.28 on 2026-04-28 20:41

import apps.mes.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('plm', '0001_initial'),
        ('pps', '0002_alter_demandforecast_confidence_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MESWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wo_number', models.CharField(max_length=30)),
                ('quantity_to_build', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('quantity_completed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_scrapped', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='dispatched', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('rush', 'Rush')], default='normal', max_length=10)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_work_orders_completed', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_work_orders_dispatched', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mes_work_orders', to='plm.product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mes_work_orders', to='pps.productionorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'MES Work Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MESWorkOrderOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('operation_name', models.CharField(max_length=255)),
                ('setup_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('run_minutes_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('planned_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_good_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_scrap_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_rework_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('setup', 'Setup'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_active_operations', to=settings.AUTH_USER_MODEL)),
                ('routing_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mes_work_order_operations', to='pps.routingoperation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mes_work_order_operations', to='pps.workcenter')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='mes.mesworkorder')),
            ],
            options={
                'verbose_name': 'MES Work Order Operation',
                'ordering': ['work_order', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction_number', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('sop', 'Standard Operating Procedure'), ('setup_sheet', 'Setup Sheet'), ('quality_check', 'Quality Check'), ('safety', 'Safety Procedure'), ('other', 'Other')], default='sop', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_instructions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Instruction',
                'ordering': ['instruction_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkInstructionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(help_text='e.g. 1.0, 1.1, 2.0', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.mes.models._work_instruction_upload_path)),
                ('video_url', models.URLField(blank=True)),
                ('change_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mes.workinstruction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_instruction_versions_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Instruction Version',
                'ordering': ['instruction', '-created_at'],
                'unique_together': {('instruction', 'version')},
            },
        ),
        migrations.AddField(
            model_name='workinstruction',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mes.workinstructionversion'),
        ),
        migrations.AddField(
            model_name='workinstruction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_instructions', to='plm.product'),
        ),
        migrations.AddField(
            model_name='workinstruction',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_instructions_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workinstruction',
            name='routing_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_instructions', to='pps.routingoperation'),
        ),
        migrations.AddField(
            model_name='workinstruction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='ShopFloorOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('default_work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_operators', to='pps.workcenter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_floor_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Floor Operator',
                'ordering': ['badge_number'],
                'unique_together': {('tenant', 'badge_number')},
            },
        ),
        migrations.CreateModel(
            name='AndonAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_number', models.CharField(max_length=30)),
                ('alert_type', models.CharField(choices=[('quality', 'Quality'), ('material', 'Material'), ('equipment', 'Equipment'), ('safety', 'Safety'), ('other', 'Other')], default='quality', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('raised_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_alerts_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_alerts_resolved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='andon_alerts', to='pps.workcenter')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_alerts', to='mes.mesworkorder')),
                ('work_order_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_alerts', to='mes.mesworkorderoperation')),
            ],
            options={
                'verbose_name': 'Andon Alert',
                'ordering': ['-severity', '-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkInstructionAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction_version', models.CharField(help_text='Snapshot of the version string at ack time.', max_length=20)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('signature_text', models.CharField(max_length=120)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='mes.workinstruction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_instruction_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Instruction Acknowledgement',
                'ordering': ['-acknowledged_at'],
                'indexes': [models.Index(fields=['tenant', 'user'], name='mes_workins_tenant__2a0550_idx'), models.Index(fields=['tenant', 'instruction'], name='mes_workins_tenant__666851_idx')],
                'unique_together': {('tenant', 'instruction', 'user', 'instruction_version')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='workinstruction',
            unique_together={('tenant', 'instruction_number')},
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('good_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('scrap_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rework_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('scrap_reason', models.CharField(blank=True, choices=[('material_defect', 'Material Defect'), ('setup_error', 'Setup Error'), ('tooling', 'Tooling'), ('process', 'Process'), ('operator_error', 'Operator Error'), ('other', 'Other')], max_length=30)),
                ('cycle_time_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reported_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_production_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_order_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='mes.mesworkorderoperation')),
            ],
            options={
                'verbose_name': 'Production Report',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['tenant', 'work_order_operation', 'reported_at'], name='mes_product_tenant__b5627d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('start_job', 'Start Job'), ('pause_job', 'Pause Job'), ('resume_job', 'Resume Job'), ('stop_job', 'Stop Job')], max_length=15)),
                ('recorded_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='mes.shopflooroperator')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_order_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='mes.mesworkorderoperation')),
            ],
            options={
                'verbose_name': 'Operator Time Log',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['tenant', 'operator', 'recorded_at'], name='mes_operato_tenant__a52a59_idx'), models.Index(fields=['tenant', 'work_order_operation', 'action'], name='mes_operato_tenant__527194_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mesworkorderoperation',
            index=models.Index(fields=['tenant', 'status'], name='mes_meswork_tenant__39c300_idx'),
        ),
        migrations.AddIndex(
            model_name='mesworkorderoperation',
            index=models.Index(fields=['tenant', 'current_operator'], name='mes_meswork_tenant__b73c51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mesworkorderoperation',
            unique_together={('work_order', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='mesworkorder',
            unique_together={('tenant', 'wo_number')},
        ),
        migrations.AddIndex(
            model_name='andonalert',
            index=models.Index(fields=['tenant', 'status', 'severity'], name='mes_andonal_tenant__04fcf6_idx'),
        ),
        migrations.AddIndex(
            model_name='andonalert',
            index=models.Index(fields=['tenant', 'work_center', 'status'], name='mes_andonal_tenant__bbe52f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='andonalert',
            unique_together={('tenant', 'alert_number')},
        ),
    ]
