# Generated by Django 4.2.28 on 2026-05-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eam', '0001_initial'),
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='andonalert',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_alerts', to='eam.asset'),
        ),
        migrations.AddField(
            model_name='mesworkorder',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_work_orders', to='eam.tool'),
        ),
    ]
