# Generated by Django 4.2.28 on 2026-05-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
        ('mes', '0002_andonalert_asset_mesworkorder_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopflooroperator',
            name='employee',
            field=models.OneToOneField(blank=True, help_text='Soft link to labor.Employee; enables labor-cost cross-module hooks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_floor_operator', to='labor.employee'),
        ),
    ]
