# Generated by Django 4.2.28 on 2026-05-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
        ('mes', '0003_shopflooroperator_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='andonalert',
            name='source_anomaly',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andon_alert', to='iot.anomalydetection'),
        ),
    ]
