# Generated by Django 4.2.28 on 2026-04-26 14:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plm', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('bom_type', models.CharField(choices=[('ebom', 'Engineering BOM (EBOM)'), ('mbom', 'Manufacturing BOM (MBOM)'), ('sbom', 'Service BOM (SBOM)')], default='ebom', max_length=10)),
                ('version', models.CharField(default='A', max_length=10)),
                ('revision', models.CharField(default='01', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default BOM of this type for the product (used by cost roll-up cascade and MRP).')),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='plm.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'product', 'bom_type', 'version', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='SubstitutionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('condition_text', models.TextField(blank=True, help_text='Free-text rule (e.g. "any 10kΩ 1% resistor in 0805 package").')),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('original_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitution_rules_original', to='plm.product')),
                ('substitute_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitution_rules_substitute', to='plm.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BOMSyncMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('in_sync', 'In Sync'), ('drift_detected', 'Drift Detected'), ('manual_override', 'Manual Override')], default='pending', max_length=20)),
                ('drift_summary', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_targets', to='bom.billofmaterials')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_syncs', to=settings.AUTH_USER_MODEL)),
                ('target_bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_sources', to='bom.billofmaterials')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source_bom', 'target_bom')},
            },
        ),
        migrations.CreateModel(
            name='BOMRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=10)),
                ('revision', models.CharField(max_length=10)),
                ('revision_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('engineering', 'Engineering'), ('rollback', 'Rollback')], default='minor', max_length=20)),
                ('change_summary', models.TextField(blank=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='bom.billofmaterials')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_revisions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('unit_of_measure', models.CharField(choices=[('ea', 'Each'), ('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound'), ('m', 'Meter'), ('cm', 'Centimeter'), ('l', 'Liter'), ('ml', 'Milliliter'), ('box', 'Box'), ('set', 'Set')], default='ea', max_length=10)),
                ('scrap_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage scrap factor — added to effective demand.', max_digits=6)),
                ('is_phantom', models.BooleanField(default=False, help_text='Phantom assemblies are exploded transparently and never appear in MRP.')),
                ('reference_designator', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bom.billofmaterials')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bom_lines', to='plm.product')),
                ('parent_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bom.bomline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name': 'BOM Line',
                'ordering': ['bom', 'sequence', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BOMCostRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('overhead_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tooling_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('other_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('bom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rollup', to='bom.billofmaterials')),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_rollups', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='CostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_type', models.CharField(choices=[('material', 'Material'), ('labor', 'Labor'), ('overhead', 'Overhead'), ('tooling', 'Tooling'), ('other', 'Other')], default='material', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('vendor', 'Vendor Quote'), ('computed', 'Computed')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_elements', to='plm.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['product__sku', 'cost_type'],
                'unique_together': {('tenant', 'product', 'cost_type')},
            },
        ),
        migrations.CreateModel(
            name='BOMSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Mapping Created'), ('updated', 'Updated'), ('drift', 'Drift Detected'), ('reconciled', 'Reconciled')], max_length=20)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_sync_log_entries', to=settings.AUTH_USER_MODEL)),
                ('sync_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='bom.bomsyncmap')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sync_map', '-timestamp'], name='bom_bomsync_sync_ma_65e7de_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlternateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 = preferred substitute. Lower number = higher priority.')),
                ('substitution_type', models.CharField(choices=[('direct', 'Direct (drop-in)'), ('approved', 'Approved Equivalent'), ('emergency', 'Emergency / Last Resort'), ('one_to_one', 'One-to-One'), ('one_to_many', 'One-to-Many')], default='approved', max_length=20)),
                ('usage_rule', models.TextField(blank=True, help_text='Conditions under which this alternate may be used.')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('alternate_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternate_for_lines', to='plm.product')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_approvals', to=settings.AUTH_USER_MODEL)),
                ('bom_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternates', to='bom.bomline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['bom_line', 'priority'],
                'unique_together': {('bom_line', 'alternate_component')},
            },
        ),
    ]
