# Generated by Django 4.2.28 on 2026-04-26 18:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='bomline',
            name='scrap_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage scrap factor — added to effective demand.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
